# Generated by Django 4.0 on 2021-12-08 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('colour', models.CharField(max_length=6)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike'), (3, 'Checkmark'), (4, 'Cross')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.card')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('location', models.PositiveIntegerField(unique=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.card')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boardtag')),
            ],
        ),
        migrations.CreateModel(
            name='CardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Comment'), (2, 'List'), (3, 'Attachment')], default=1)),
                ('contents', models.CharField(max_length=2048)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.list'),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.IntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Read'), (4, 'Write')], default=3)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['card', 'author'], name='board_react_card_id_b73754_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('card', 'author', 'reaction'), name='uq_reaction'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['board'], name='board_list_board_i_ef4ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtag',
            index=models.Index(fields=['board', 'card'], name='board_cardt_board_i_264c86_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardtag',
            constraint=models.UniqueConstraint(fields=('board', 'card', 'tag'), name='uq_card_tag'),
        ),
        migrations.AddIndex(
            model_name='cardcontent',
            index=models.Index(fields=['card', 'author'], name='board_cardc_card_id_3d8873_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['board', 'list', 'author'], name='board_card_board_i_43b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='boardtag',
            index=models.Index(fields=['board', 'name'], name='board_board_board_i_ff648f_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardtag',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uq_board_tag'),
        ),
        migrations.AddIndex(
            model_name='boardmember',
            index=models.Index(fields=['board', 'member'], name='board_board_board_i_bcbb5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardmember',
            constraint=models.UniqueConstraint(fields=('board', 'member'), name='uq_member'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['author', 'title'], name='board_board_author__6d9886_idx'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='uq_board'),
        ),
    ]
